---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: echo-server
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    hostname: echo-server.pickles.pdx.dev.eng.kiddom.cloud
    protocol: HTTPS
    port: 443
    tls:
      certificateRefs:
      - kind: Secret
        name: acme-tls
        namespace: istio-system
