---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: zerotrust
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: '*.pickles.pdx.dev.eng.kiddom.cloud'
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway.networking.k8s.io/name: zerotrust
  - name: https
    hostname: '*.pickles.pdx.dev.eng.kiddom.cloud'
    protocol: HTTPS
    port: 443
    tls:
      certificateRefs:
      - kind: Secret
        name: acme-tls
        namespace: istio-system
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway.networking.k8s.io/name: zerotrust
