---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo-server
spec:
  parentRefs:
  - name: echo-server
  hostnames:
  - "echo-server.pickles.pdx.dev.eng.kiddom.cloud"
  rules:
  - backendRefs:
    - name: echo-server
      port: 80
