apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./configmap.yaml
- ./deployment.yaml
- ./ingress.yaml
- ./service.yaml
- ./virtualservice.yaml
- ./gateway.networking.k8s.io_gateway_echo-server.yaml
- ./gateway.networking.k8s.io_httproute_echo-server.yaml
